apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
  creationTimestamp: null
  labels:
    io.kompose.service: stepbot
  name: stepbot
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: stepbot
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
      creationTimestamp: null
      labels:
        io.kompose.service: stepbot
    spec:
      containers:
        - image: 192.168.10.121:30000/stepbot:1.0.73
          name: stepbot
          resources: {}
          imagePullPolicy: Always  
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred 
