apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: stepbot
  name: stepbot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: stepbot
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: stepbot
    spec:
      containers:
        - image: stepbot/1.0.0:latest
          name: stepbot
          resources: {}
      restartPolicy: Always
status: {}
